#!/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

#
# Execute the given backup then:
#  - write the output inside a log file
#  - invoke all executable scripts inside /etc/backup-data.hooks/ directory
#

backup=$1
ts=$(date +%Y%m%d%H%M)
cmd="/sbin/e-smith/backup-data -b $backup"
out_dir="/var/log/backup"

if [ ! -d $out_dir ]; then
    mkdir -p $out_dir
fi

set -o pipefail
log="${out_dir}/backup-${backup}-${ts}.log"
output=$($cmd 2>&1 | tee "$log")
exit_code=$?

# exec all scripts inside /etc/backup-data.hooks
for file in /etc/backup-data.hooks/*; do
    [ -f "$file" ] && [ -x "$file" ] && "$file" "$backup" "$log" $exit_code
done

set +o pipefail
exit $exit_code
