#!/usr/bin/perl -w
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::Build::CreateLinks  qw(:all);


#--------------------------------------------------
# actions for nethserver-backup-data-update event
#--------------------------------------------------

my $event = "nethserver-backup-data-update";

event_actions($event, 'initialize-default-databases' => '00');
templates2events("/etc/cron.d/backup-data",  $event);
templates2events("/etc/davfs2/davfs2.conf",  $event);
templates2events("/etc/davfs2/secrets",  $event);


#--------------------------------------------------
# actions for nethserver-backup-data-save event
#--------------------------------------------------

$event = "nethserver-backup-data-save";
templates2events("/etc/cron.d/backup-data",  $event);
templates2events("/etc/davfs2/davfs2.conf",  $event);
templates2events("/etc/davfs2/secrets",  $event);

#--------------------------------------------------
# actions for nethserver-backup-data-uninstall event
#--------------------------------------------------

$event = "nethserver-backup-data-uninstall";
unlink("/etc/cron.d/backup-data");

#--------------------------------------------------
# actions for pre-backup-data event
#--------------------------------------------------

$event = "pre-backup-data";
event_actions($event, 
   'mount-usb' => '70',
   'mount-cifs' => '70',
   'mount-nfs' => '70',
   'mount-webdav' => '70',
);

#--------------------------------------------------
# actions for post-backup-data event
#--------------------------------------------------

$event = "post-backup-data";
event_actions($event, 
   'cleanup-data-duplicity' => '70',
   'disk-usage' => '70',
   'umount-usb' => '80',
   'umount-cifs' => '80',
   'umount-nfs' => '80',
   'umount-webdav' => '80',
);


#--------------------------------------------------
# actions for pre-restore-data event
#--------------------------------------------------

$event = "pre-restore-data";
event_actions($event, 
   'mount-usb' => '10',
   'mount-cifs' => '10',
   'mount-nfs' => '10',
   'mount-webdav' => '10',
);

#--------------------------------------------------
# actions for post-restore-data event
#--------------------------------------------------

$event = "post-restore-data";
event_actions($event, 
   'umount-usb' => '90',
   'umount-cifs' => '90',
   'umount-nfs' => '90',
   'umount-webdav' => '90',
);

exit;
