#!/usr/bin/perl

#
# Copyright (C) 2018 Nethesis S.r.l.
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::Build::CreateLinks  qw(:all);

#--------------------------------------------------
# actions for nethserver-backup-data-update event
#--------------------------------------------------

my $event = "nethserver-backup-data-update";

event_actions($event, 'initialize-default-databases' => '00');
templates2events("/etc/cron.d/backup-data",  $event);
templates2events("/etc/davfs2/davfs2.conf",  $event);
templates2events("/etc/davfs2/secrets",  $event);
templates2events("/etc/backup-data.d/nethserver-backup-data.include",  $event);


#--------------------------------------------------
# actions for nethserver-backup-data-save event
#--------------------------------------------------

$event = "nethserver-backup-data-save";
templates2events("/etc/cron.d/backup-data",  $event);
templates2events("/etc/davfs2/davfs2.conf",  $event);
templates2events("/etc/davfs2/secrets",  $event);
templates2events("/etc/backup-data.d/nethserver-backup-data.include",  $event);
templates2events("/etc/ssh/ssh_config",  $event);
event_actions($event,
   'nethserver-backup-data-ssh' => '40',
);


#--------------------------------------------------
# actions for post-backup-data event
#--------------------------------------------------

$event = "post-backup-data";
event_actions($event, 
   'cleanup-data-duplicity' => '70',
);

exit;
