#!/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

#
# Cleanup backup logs following logrotate configuration
#

times=$(/sbin/e-smith/config getprop logrotate Times)
rotate=$(/sbin/e-smith/config getprop logrotate Rotate)
dir="/var/log/backup/"
days=0

if [ "$rotate" == "daily" ]; then
    days=$times
elif [ "$rotate" == "weekly" ]; then
    days=$(($times*7))
elif [ "$rotate" == "monthly" ]; then
    days=$(($times*30))
else
    echo "Invalid rotate policy"
    exit 1
fi

if [ ! -d $dir ]; then
    exit 0
fi

find $dir -mtime +$days -delete
