#!/usr/bin/perl -w

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# Original work:
# copyright (C) 2006-2007 Jean-Paul Leclere <jean-paul@leclere.org>
# copyright (C) 2007 Charlie Brady <charlieb@e-smith.com>
#
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use Errno;
use esmith::ConfigDB;
use NethServer::BackupData;
use File::Path qw(make_path);

sub ldie;

my $confdb = esmith::ConfigDB->open;
my $backupwk = $confdb->get('backup-data') or die "No backup-data db entry found\n";
my $VFSType = $backupwk->prop('VFSType') || 'UNKNOWN';
our $mntdir = $backupwk->prop('Mount') || '/mnt/backup';
my $err = 0;
my $mntdone = 0;

exit 0 unless ($VFSType eq 'usb');
my $usblabel = $backupwk->prop('USBLabel') || die "No USBLabel set";

our $b = new NethServer::BackupData();

# get the device name
my $device = qx( /sbin/blkid -u filesystem -L $usblabel);
chomp $device; # remove trailing new line

# creating mount directory
if ( ! -d $mntdir ) {
    make_path($mntdir);
}

# mount backup directory if not already mounted
if (!$b->is_mounted($device) || !$b->is_mounted($mntdir)) {
    # create mnt directory
    system("/bin/mkdir -p $mntdir");

    # mount the disk
    $err = qx(/bin/mount $device "$mntdir" 2>&1);
    if ($err) {
        $err =~s/\n/ /g;
        ldie("Error while mounting /$usblabel : " . $err);        
    }
}

$mntdone = 1;

sub ldie 
{
    my $errmsg = shift;
    system("/bin/umount", "$mntdir") if $mntdone;
    $b->bad_exit($errmsg);
}

