#!/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

set -e

EVENT=$1
BACKUP=$2
PASSWORD=$3

KEY=/var/lib/nethserver/backup/restic.key

if [ -z $BACKUP ] || [ -z $PASSWORD ]; then
   echo "Usage: $0 <user> <host> <port> <password_file>"
   exit 1
fi

USER=$(/sbin/e-smith/db backups getprop $BACKUP SftpUser)
HOST=$(/sbin/e-smith/db backups getprop $BACKUP SftpHost)
PORT=$(/sbin/e-smith/db backups getprop $BACKUP SftpPort)

if [ ! -f /var/lib/nethserver/backup/restic.key ]; then
    ssh-keygen -N '' -f $KEY
fi

sshpass -f $PASSWORD /usr/bin/ssh-copy-id -i $KEY".pub" -p $PORT $USER@$HOST

if [ -f $PASSWORD ]; then
    rm -f $PASSWORD
fi
