#!/usr/bin/perl -w

#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use Errno;
use esmith::ConfigDB;
use NethServer::BackupData;

my $confdb = esmith::ConfigDB->open;
my $backupwk = $confdb->get('backup-data') or die "No backup-data db entry found\n";
my $VFSType = $backupwk->prop('VFSType') || 'UNKNOWN';
my $webdavurl = $backupwk->prop('WebDAVUrl');
my $mntdir = $backupwk->prop('Mount') || '/mnt/backup';
my $err = 0;

exit 0 unless ($VFSType eq 'webdav');

my $b = new NethServer::BackupData();

# check if backp directory is mounted and umount
if ($b->is_mounted("$webdavurl") or $b->is_mounted($mntdir)) {
    system("/bin/umount", "$mntdir");
}

exit 0;
