#!/usr/bin/perl -w

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use Errno;
use esmith::ConfigDB;
use NethServer::BackupData;

# The action can be invoked from post-backup-data event or directly from a script.
# If invoked from a script, just pass the name of the backup.
my $name = shift || '';

my $backupwk;
my $mntdir;
my $confdb = esmith::ConfigDB->open;
if ($name eq 'post-backup-data' || $name eq 'post-restore-data' || $name eq '') {
   $backupwk = $confdb->get('backup-data') || die "No backup-data db entry found\n";;
   $mntdir = $backupwk->prop('Mount') || '/mnt/backup';
} else {
   my $db = esmith::ConfigDB->open_ro('backups') || die("Could not open backups db\n");
   $backupwk = $db->get($name) || die("No backup '$name' found");
   $mntdir = "/mnt/backup-$name";
}

my $VFSType = $backupwk->prop('VFSType') || 'UNKNOWN';
my $nfshost = $backupwk->prop('NFSHost');
my $nfsshare = $backupwk->prop('NFSShare');
my $err = 0;

exit 0 unless ($VFSType eq 'nfs');

my $b = new NethServer::BackupData();


# check if backp directory is mounted and umount it
if ($b->is_mounted("\/$nfshost(.*)\/$nfsshare") or $b->is_mounted($mntdir)) {
    system("/bin/umount", "$mntdir");
}

exit 0;

