#!/usr/bin/python

#
# Copyright (C) 2015 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import gettext
import json
import sys
import re
import subprocess

serverid = ''

try:
    p = subprocess.Popen(['/sbin/e-smith/db', 'backups', 'getprop', 'backup-data', 'status'], stdout=subprocess.PIPE)
    status, err = p.communicate()
except:	
    exit(1)

if(status.rstrip() == 'disabled'):
    gettext.textdomain('nethserver-backup-data')
    msg = {
        "action": {
            "label": gettext.gettext('Enable backup'),
            "url": '/BackupData'
        },
        "text": gettext.gettext('Proceed with configuration of data backup'),
        "icon": "edit"
    }
    json.dump(msg, sys.stdout)
	    

